FROM python:3.12-slim

# Install Git
RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Copy the app
ADD . /app
WORKDIR /app

# Install dependencies
RUN uv sync