[project]
name = "middleware"
version = "0.1.0"
description = "Starfish's middleware implementation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.5",
    "loguru>=0.7.2",
    "orjson>=3.10.7",
    "pydantic>=2.8.2",
    "pydantic-settings>=2.4.0",
    "websockets>=13.1",
    "redis>=5.1.0",
]

[tool.black]
line-length = 100
include = "\\.pyi?$"

[tool.isort]
profile = "black"

[tool.taskipy.tasks]
lint = "black . && isort . && flake8 ."
test = "python test.py"

[tool.uv]
dev-dependencies = [
    "black>=24.8.0",
    "flake8>=7.1.1",
    "pre-commit>=3.8.0",
    "taskipy>=1.13.0",
    "isort>=5.13.2",
    "ruff>=0.6.7",
]

[tool.uv.sources]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
